///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace pdftest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the pdftestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("fd51686f-c033-49c4-865a-33b11254ef4b")]
    public partial class pdftestRepository : RepoGenBaseFolder
    {
        static pdftestRepository instance = new pdftestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the pdftestRepository element repository.
        /// </summary>
        [RepositoryFolder("fd51686f-c033-49c4-865a-33b11254ef4b")]
        public static pdftestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public pdftestRepository() 
            : base("pdftestRepository", "/", null, 0, false, "fd51686f-c033-49c4-865a-33b11254ef4b", ".\\RepositoryImages\\pdftestRepositoryfd51686f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fd51686f-c033-49c4-865a-33b11254ef4b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class pdftestRepositoryFolders
    {
    }
#pragma warning restore 0436
}